version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: kp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    ports:
      - "5433:5432"

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

volumes:
  minio_data:
